PROMPT DROP TRIGGERS;
DROP TRIGGER BORROW_UPDATE_CONSTRAINT;
DROP TRIGGER RETURN_UPDATE_CONSTRAINT;
DROP TRIGGER RENEWED_BOOK_CONSTRAINT;
DROP TRIGGER BORROW_RESERVEDBOOK_CONSTRAINT;


PROMPT DROP TABLES;
DROP TABLE BOOK CASCADE CONSTRAINT;
DROP TABLE STUDENT CASCADE CONSTRAINT;
DROP TABLE BORROW CASCADE CONSTRAINT;
DROP TABLE RENEW CASCADE CONSTRAINT;
DROP TABLE RESERVE CASCADE CONSTRAINT;

